-- krx.order_book_hose definition

CREATE TABLE iceberg.krx.order_book_hose (
  `Trade Date` STRING,
  `Market ID` STRING,
  Symbol STRING,
  Currency STRING,
  `Board Type` STRING,
  `Order Date` STRING,
  `Order Time` STRING,
  Session STRING,
  `Modify/Cancel` STRING,
  `Order Accept #` STRING,
  `Orig Order Accept #` STRING,
  Side STRING,
  `BRK #` STRING,
  BRK STRING,
  PIN STRING,
  `Acct No` STRING,
  Name STRING,
  `Market Maker Order` STRING,
  `Client/House Classification Code` STRING,
  `Invest Type` STRING,
  `Foreigner Investor type` STRING,
  `Order Type` STRING,
  `Order Price` STRING,
  `Order VOL` STRING,
  `Order Condition` STRING,
  LTP STRING,
  `Execution Price` STRING,
  `Immed. Matched VOL` STRING,
  `Matched VOL` STRING,
  `Order Rqty` STRING,
  `Order Price-LTP` STRING,
  `Matched Ratio` STRING,
  `Buy Up/Sell Down Amt` STRING,
  `Buy Up/Sell Down Tick` STRING,
  `New High/Low Price` STRING,
  `Order Status` STRING,
  `Icd-Bug Qty` STRING,
  `Expected execution price` STRING,
  `Expected execution volume` STRING,
  `Short Sell Indicator` STRING,
  `Trader No` STRING,
  `Trader Name` STRING,
  `Reference Sequence No.` STRING,
  `Order ID` STRING,
  `Orig Order ID` STRING,
  year STRING,
  month STRING)
USING iceberg
PARTITIONED BY (year, month)
LOCATION 's3a://iceberg/krx.db/order_book_hose'
TBLPROPERTIES (
  'current-snapshot-id' = '2352573857472434017',
  'format' = 'iceberg/parquet',
  'format-version' = '2',
  'write.parquet.compression-codec' = 'zstd');

-- krx.order_book_hnx definition

CREATE TABLE iceberg.krx.order_book_hnx (
  trade_date STRING,
  market_id STRING,
  board_id STRING,
  issue_code STRING,
  order_accept_time STRING,
  member_id STRING,
  sell_buy_classification_code STRING,
  account_number STRING,
  order_type_code STRING,
  order_condition_code STRING,
  client_house_classification_code STRING,
  investor_classification_code STRING,
  order_date STRING,
  order_reject_reason_code STRING,
  order_quantity STRING,
  order_price STRING,
  public_quantity STRING,
  condition_price STRING,
  order_reception_number STRING,
  original_order_reception_number STRING,
  original_order_type_code STRING,
  session_id STRING,
  order_remaining_quantity STRING,
  message_sequence STRING,
  replace_cancel STRING,
  quote_request_type STRING,
  automated_cancel STRING,
  order_id STRING,
  original_order_id STRING,
  foreign_investor_type_code STRING,
  year STRING,
  month STRING)
USING iceberg
PARTITIONED BY (year, month)
LOCATION 's3a://iceberg/krx.db/order_book_hnx'
TBLPROPERTIES (
  'current-snapshot-id' = '8874852823419099909',
  'format' = 'iceberg/parquet',
  'format-version' = '2',
  'write.parquet.compression-codec' = 'zstd');

-- krx.trade_book_hose definition

CREATE TABLE iceberg.krx.trade_book_hose (
  `Trade Date` STRING,
  `Market ID` STRING,
  Symbol STRING,
  Currency STRING,
  `Board Type` STRING,
  `Trade #` STRING,
  Time STRING,
  Session STRING,
  `Execution_Exec Price` STRING,
  `Execution_Exec Price - LTP` STRING,
  Execution_Volume STRING,
  Execution_Value STRING,
  Execution_LTP STRING,
  `Execution_New High/Low Price` STRING,
  `Buy_Order Date` STRING,
  `Buy_Order Time` STRING,
  `Buy_Order Accept #` STRING,
  `Buy_BRK #` STRING,
  Buy_BRK STRING,
  Buy_PIN STRING,
  `Buy_Acct No` STRING,
  Buy_Name STRING,
  `Buy_Client/House Classification Code` STRING,
  `Buy_Invest Type` STRING,
  `Buy_Foreigner Investor type` STRING,
  `Buy_Order Price` STRING,
  `Buy_Order VOL` STRING,
  `Buy_Trader No` STRING,
  `Buy_Trader Name` STRING,
  `Buy_Reference Sequence No.` STRING,
  `Sell_Order Date` STRING,
  `Sell_Order Time` STRING,
  `Sell_Order Accept #` STRING,
  `Sell_BRK #` STRING,
  Sell_BRK STRING,
  Sell_PIN STRING,
  `Sell_Acct No` STRING,
  Sell_Name STRING,
  `Sell_Client/House Classification Code` STRING,
  `Sell_Invest Type` STRING,
  `Sell_Foreigner Investor type` STRING,
  `Sell_Order Price` STRING,
  `Sell_Order VOL` STRING,
  `Sell_Trader No` STRING,
  `Sell_Trader Name` STRING,
  `Sell_Reference Sequence No.` STRING,
  year STRING,
  month STRING)
USING iceberg
PARTITIONED BY (year, month)
LOCATION 's3a://iceberg/krx.db/trade_book_hose'
TBLPROPERTIES (
  'current-snapshot-id' = '4279073940801430487',
  'format' = 'iceberg/parquet',
  'format-version' = '2',
  'write.parquet.compression-codec' = 'zstd');

-- krx.trade_book_hnx definition

CREATE TABLE iceberg.krx.trade_book_hnx (
  trade_date STRING,
  market_id STRING,
  board_id STRING,
  issue_code STRING,
  trade_number STRING,
  trade_time STRING,
  trade_price STRING,
  trade_quantity STRING,
  session_id STRING,
  sell_replace_cancel_classification_code STRING,
  sell_member_number STRING,
  sell_account_number STRING,
  sell_order_type_code STRING,
  sell_order_condition_code STRING,
  sell_client_house_classification STRING,
  sell_investor_classification_code STRING,
  sell_order_quantity STRING,
  sell_order_price STRING,
  buy_member_number STRING,
  buy_replace_cancel_classification_code STRING,
  buy_account_number STRING,
  buy_order_type_code STRING,
  buy_order_condition_code STRING,
  buy_client_house_classification STRING,
  buy_investor_classification_code STRING,
  buy_order_quantity STRING,
  buy_order_price STRING,
  message_sequence STRING,
  sell_order_reception_number STRING,
  buy_order_reception_number STRING,
  sell_quote_request_code STRING,
  buy_quote_request_code STRING,
  execution_price_of_spread_first STRING,
  execution_price_of_spread_second STRING,
  sell_foreign_investor_type_code STRING,
  buy_foreign_investor_type_code STRING,
  year STRING,
  month STRING)
USING iceberg
PARTITIONED BY (year, month)
LOCATION 's3a://iceberg/krx.db/trade_book_hnx'
TBLPROPERTIES (
  'current-snapshot-id' = '8939288554638065998',
  'format' = 'iceberg/parquet',
  'format-version' = '2',
  'write.parquet.compression-codec' = 'zstd');